// CHAPTER NP 04
// VARIABLE NAMES: LEGAL & ILLEGAL
// QUESTION NO 01
// 1. Declare 3 variables in one statement.
// var name = 'John', age = 30, city = 'New York';

// 2. Declare 5 legal & 5 illegal variable names.
// Legal Variable Names

// 1. myVariable
// 2. _age
// 3. cityName
// 4. my_1stVariable

// Illegal Variable Names

// 1. 1stVariable 
// 2. my-variable
// 3. my variable


// 3. Display this in your browser
// a) A heading stating “Rules for naming JS variables”
// b) Variable names can only contain ______, ______,
// ______ and ______.
// For example $my_1stVariable
// c) Variables must begin with a ______, ______ or
// _____. For example $name, _name or name
// d) Variable names are case _________
// e) Variable names should not be JS _________
