// chapter no 05
// MATH EXPRESSIONS
// QUESTION NO 01
// Write a program that take two numbers & add them in a
// new variable. Show the result in your browser.
// var num1 = 3 ;
// var num2 = 6 ;
// alert(num1 + num2)
// QUESTION NO 02
// 2. Repeat task1 for subtraction, multiplication, division &
// modulus.
// var num1 = 3 ;
// var num2 = 6 ;
// alert(num1 - num2)
// var num1 = 3 ;
// var num2 = 6 ;
// alert(num1 * num2)
// var num1 = 3 ;
// var num2 = 6 ;
// alert(num1 / num2)
// QUESTION NO 03
// 3. Do the following using JS Mathematic Expressions
// a. Declare a variable.
// answer
// Var myVariable;

// b. Show the value of variable in your browser like “Value
// after variable declaration is: ??”.
// document.write("Value after variable declaration is: " + myVariable );

// c. Initialize the variable with some number.
// myVariable = 5;


// d. Show the value of variable in your browser like “Initial
// value: 5”.
// document.write("Initial value: " + myVariable );

// e. Increment the variable.
// myVariable++;

// f. Show the value of variable in your browser like “Value
// after increment is: 6”.
// document.write("Value after increment is: " + myVariable );

// g. Add 7 to the variable.
// myVariable += 7;

// h. Show the value of variable in your browser like “Value
// document.write("Value after adding 7 is: " + myVariable );

// h. Show the value of variable in your browser like “Value
// after addition is: 13”.
// document.write("Value after decrement is: " + myVariable + "
//    13 ");
    

// i. Decrement the variable.
// myVariable--;

// j. Show the value of variable in your browser like “Value
// after decrement is: 12”.
// document.write("Value after decrement is: " + myVariable + "
//    12 ");
    
// k. Show the remainder after dividing the variable’s value
// by 3.
// var remainder = myVariable % 3;

// l. Output : “The remainder is : 0”.
// document.write("The remainder is: " + remainder + "
//     ");
//     question no 04
//     4. Cost of one movie ticket is 600 PKR. Write a script to
// store
// ticket price in a variable & calculate the cost of buying 5
// tickets
// to a movie. Example output:
// // Store ticket price in a variable
// let ticketPrice = 600;

// // Calculate the cost of buying 5 tickets
// let totalCost = ticketPrice * 5;

// // Display the result
// document.write("Cost of one movie ticket is: " + ticketPrice + " PKR
// ");
// document.write("Cost of buying 5 tickets is: " + totalCost + " PKR
// ");
// 